server:
  port: 8080
  servlet:
    context-path: /

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/zcg?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: admin

mybatis:
  ## mapper.xml扫描路径
  mapper-locations: classpath:mapping/*Mapper.xml
  ## mapper.xml的pojo包前缀
  type-handlers-package: com.exercise.web.entity